--INSERÇÃO DE CURSOS
INSERT INTO CURSO(NOME_CURSO)
	VALUES('ANÁLISE E DESENVOLVIMENTO DE SISTEMAS');
INSERT INTO CURSO(NOME_CURSO)
	VALUES('GESTÃO DE EVENTOS');
INSERT INTO CURSO(NOME_CURSO)
	VALUES('GESTÃO DE PRODUÇÃO INDUSTRIAL');
INSERT INTO CURSO(NOME_CURSO)
	VALUES('GESTÃO EMPRESARIAL');
INSERT INTO CURSO(NOME_CURSO)
	VALUES('GESTÃO HOSPITALAR');


--INSERÇÃO DE STATUS DE DISCENTE
INSERT INTO STATUS_DISCENTE(DESCRICAO_STATUS_DISCENTE)
	VALUES('EM BUSCA DE PROJETO');
INSERT INTO STATUS_DISCENTE(DESCRICAO_STATUS_DISCENTE)
	VALUES('INDISPONÍVEL');


--INSERÇÃO DE REDE
INSERT INTO REDE(DESCRICAO_REDE)
	VALUES('Portfólio Pessoal');


--INSERÇÃO DE STATUS DE PROJETO
INSERT INTO STATUS_PROJETO(DESCRICAO_STATUS_PROJETO)
	VALUES('EM BUSCA DE DISCENTE');
INSERT INTO STATUS_PROJETO(DESCRICAO_STATUS_PROJETO)
	VALUES('EM DESENVOLVIMENTO');
INSERT INTO STATUS_PROJETO(DESCRICAO_STATUS_PROJETO)
	VALUES('FINALIZADO');
INSERT INTO STATUS_PROJETO(DESCRICAO_STATUS_PROJETO)
	VALUES('SUSPENSO');


--INSERÇÃO DE NÍVEL DE HABILIDADE
INSERT INTO NIVEL_HABILIDADE(DESCRICAO_NIVEL)
	VALUES('APRENDIZ');
INSERT INTO NIVEL_HABILIDADE(DESCRICAO_NIVEL)
	VALUES('PRATICANTE');
INSERT INTO NIVEL_HABILIDADE(DESCRICAO_NIVEL)
	VALUES('VERSÁTIL');
INSERT INTO NIVEL_HABILIDADE(DESCRICAO_NIVEL)
	VALUES('ESPECIALISTA');


--INSERÇÃO DE ORDEM_AUTORIA
INSERT INTO ORDEM_AUTORIA(DESCRICAO_ORDEM_AUTORIA)
	VALUES('AUTORIA PRINCIPAL');
INSERT INTO ORDEM_AUTORIA(DESCRICAO_ORDEM_AUTORIA)
	VALUES('CO-AUTORIA');
INSERT INTO ORDEM_AUTORIA(DESCRICAO_ORDEM_AUTORIA)
	VALUES('DESENVOLVIMENTO TÉCNICO');
INSERT INTO ORDEM_AUTORIA(DESCRICAO_ORDEM_AUTORIA)
	VALUES('APOIO TÉCNICO');